server:
  port: 19090
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片。默认是索引为0的分片。redis集群只有db0
    database: 0
    # Redis服务器地址
    host: x.x.x.x
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 2000s
    # 配置文件中添加 lettuce.pool 相关配置，则会使用到lettuce连接池
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 60s
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 5
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
